[hello] 
  other = "Hello From Service API"

[unknownroute]
  other = "{{.Method}} cho {{.Route}} is not supported"

[internal] 
  other = "please try again"

[required]
  other = "{{.Field}} is a required field"

[ws] 
  other = "Can't established ws connection"

