[hello] 
  other = "Xin Chao"

[unknownroute]
  other = "{{.Method}} cho {{.Route}} khong duoc ho tro"

[internal] 
  other = "Xin vui long thu lai sau"

[required]
  other = "{{.Field}} là trường bắt buộc."

[ws]
  other = "Khong the lien ket websocket"
